 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: Ultrasonic.h
 *
 * Description: header file for the Ultrasonic
 *
 * Author: Amr Essam
 *
 *******************************************************************************/

#ifndef UTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ULTRASONIC_TRIGGER_PORT   PORTB_ID
#define ULTRASONIC_TRIGGER_PIN    PIN5_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 *  Function responsible for initialize Ultrasonic.
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the
 *  GPIO driver.
 */
void Ultrasonic_int(void);


/*
 * Description :
 * Function responsible for  Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_trigger(void);


/*
 * Description :
 * Function responsible for:
 * Send the trigger pulse by using Ultrasonic_Trigger function
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);



/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);



#endif
